export enum AvailableSlotErrorType {
    SLOT_ALREADY_EXISTS = 'SLOT_ALREADY_EXISTS',
    SLOT_NOT_FOUND = 'SLOT_NOT_FOUND',
    INVALID_SLOT_TIME = 'INVALID_SLOT_TIME',
    UNAUTHORIZED = 'UNAUTHORIZED',
    INVALID_SLOT_DATE = 'INVALID_SLOT_DATE',
    VALIDATION_ERROR = 'VALIDATION_ERROR'
}
