export enum SchedulingErrorType {
    SCHEDULING_CONFLICT = 'SCHEDULING_CONFLICT',
    SCHEDULING_NOT_FOUND = 'SCHEDULING_NOT_FOUND',
    SCHEDULING_IN_PAST = 'SCHEDULING_IN_PAST',
    UNAUTHORIZED = 'UNAUTHORIZED',
    VALIDATION_ERROR = 'VALIDATION_ERROR'
}
