export enum UserErrorType {
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    UNAUTHORIZED = 'UNAUTHORIZED',
    VALIDATION_ERROR = 'VALIDATION_ERROR'
}
